#spring.h2.console.enabled=true
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:mysql://localhost:3306/springboot
spring.datasource.username=jinwoo
spring.datasource.password=pass
